# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dy < Formula
  desc "Construct YAML from a directory tree"
  homepage "https://github.com/sampointer/dy"
  version "0.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sampointer/dy/releases/download/v0.3.0/dy_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "b45ca462057c7ac7d04ce9bc08c3046cfa9cc1e883b9c73ff586a191f7ff639e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sampointer/dy/releases/download/v0.3.0/dy_0.3.0_Darwin_arm64.tar.gz"
      sha256 "26aad9bb2b0ee8a8a6477d80902a602d5c80ae32c9bdd7269e91c569555dce0a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sampointer/dy/releases/download/v0.3.0/dy_0.3.0_Linux_x86_64.tar.gz"
      sha256 "46fe2656042649baeff0a92a7440be5ad8756489ecffc2fe117ae8a78aeeb83d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sampointer/dy/releases/download/v0.3.0/dy_0.3.0_Linux_arm64.tar.gz"
      sha256 "1fa04fd7227363af8f1787fea48aab034ed518d8171bcbbf1b0de41726f6398d"
    end
  end

  def install
    bin.install "dy"
  end
end
