# This file was generated by GoReleaser. DO NOT EDIT.
class Dy < Formula
  desc "Construct YAML from a directory tree"
  homepage "https://github.com/sampointer/dy"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sampointer/dy/releases/download/v0.2.1/dy_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "5971256edd00978909eb063281cb3182baf4d361cd18574f1119f1d60e9b5446"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sampointer/dy/releases/download/v0.2.1/dy_0.2.1_Linux_x86_64.tar.gz"
      sha256 "11926458773a5a271863a049fd29711a3d952242a741671b507419a9ae48bb6e"
    end
  end

  def install
    bin.install "dy"
  end
end
